import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

import { createTerminal, instantiateGhosttyWasm, readResponse, writeString } from './wasmBindings'

/**
 * The shipped core answers a cursor position report.
 *
 * `main/effects.test.ts` already covers this behaviour thoroughly, but against
 * `vendor-main/ghostty-vt.wasm` through the raw ABI. This pins the same thing
 * one layer up — the binary that actually ships, reached the way the engine
 * reaches it — because a *local* shell depends on it in a way no remote
 * session does.
 *
 * ConPTY opens by writing `ESC [ 6 n` and emits nothing further until it gets
 * an answer. Over SSH an unanswered DSR costs a few full-screen programs their
 * timeout; on a local pane the shell never starts at all, and the pane just
 * sits blank. The reply is generated by the core, drained by
 * `GhosttyEngine.drainResponses`, and sent back out through the same channel
 * as keystrokes.
 *
 * Discovered by writing `wr-local`'s tests the obvious way and watching a shell
 * that should print one word produce exactly six bytes and hang. See
 * docs/LOCAL_SHELL_PLAN.md, "What Phase 1 actually did".
 */

const here = dirname(fileURLToPath(import.meta.url))
const WASM = join(here, 'vendor/ghostty-vt.wasm')

const COLS = 80
const ROWS = 24

async function boot() {
  const bytes = readFileSync(WASM)
  const wasm = await instantiateGhosttyWasm(
    bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer,
  )
  const term = createTerminal(wasm, COLS, ROWS, {
    // A byte budget, not a line count.
    scrollbackLimit: 4 * 1024 * 1024,
    fgColor: 0xcccccc,
    bgColor: 0x000000,
    cursorColor: 0,
  })
  if (!term) throw new Error('createTerminal returned 0')
  return { wasm, term }
}

function drain(wasm: Awaited<ReturnType<typeof boot>>['wasm'], term: number): string {
  let out = ''
  for (;;) {
    const chunk = readResponse(wasm, term)
    if (!chunk) return out
    out += new TextDecoder().decode(chunk)
  }
}

describe('cursor position report from the shipped core', () => {
  it('answers ESC[6n, which is what lets a local shell start', async () => {
    const { wasm, term } = await boot()
    writeString(wasm, term, '\x1b[6n')

    // The assertion that matters is simply that *something* comes back. An
    // empty string here means every local pane opens blank.
    expect(drain(wasm, term)).toMatch(/^\x1b\[\d+;\d+R$/)
  })

  it('reports where the cursor actually is, not a fixed position', async () => {
    const { wasm, term } = await boot()
    // Parked somewhere unambiguous, so a hardcoded `1;1R` would fail. CPR is
    // 1-based in both axes.
    writeString(wasm, term, '\x1b[5;9H\x1b[6n')

    expect(drain(wasm, term)).toBe('\x1b[5;9R')
  })

  it('answers every query in a burst rather than only the first', async () => {
    const { wasm, term } = await boot()
    // ConPTY's opening exchange is not always a lone DSR, and a queue that
    // answered once and stopped would strand the shell just as effectively.
    writeString(wasm, term, '\x1b[6n\x1b[6n')

    expect(drain(wasm, term)).toBe('\x1b[1;1R\x1b[1;1R')
  })
})
