[package]
name = "wr-telnet"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
wr-core = { path = "../wr-core" }
async-trait = "0.1"
tokio.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
