import type { ConnectionSource } from '../lib/connection'
import { allLeaves, canSplitLeaf, closeLeaf, findLeaf, firstLeaf, splitLeaf, updateLeaf } from '../lib/paneTree'
import type { PaneLeaf, PaneNode, Tab } from '../types'
import { isBlankTab, leafTitle } from './tabOps'

export interface TabsState {
  tabs: Tab[]
  activeTabId: string | null
}

/** Every action maps close to 1:1 onto a function that used to call
 * `setTabs`/`setActiveTabId` directly in App.tsx. New ids (a fresh tab, a
 * popped-out tab) are generated by the caller — via tabOps.ts's blankTab/
 * newTabId, exactly as before — and carried in on the action, rather than
 * generated inside the reducer, so the reducer stays a deterministic
 * function of (state, action) with nothing to mock in a test. */
export type TabsAction =
  | { type: 'restored'; tabs: Tab[]; activeTabId: string | null }
  | { type: 'tabOpened'; tab: Tab }
  | { type: 'tabClosed'; tabId: string }
  | { type: 'tabSelected'; tabId: string }
  | { type: 'tabsReordered'; draggedId: string; targetId: string }
  | { type: 'paneReconnected'; tabId: string; paneId: string }
  | { type: 'workspaceMaterialized'; restored: Tab[]; originTabId: string | null }
  | {
      type: 'paneConnected'
      tabId: string
      paneId: string
      source: ConnectionSource
      backspaceSendsCtrlH: boolean | null
      autoReconnect: boolean | null
      /** The saved session's name, when connecting through one. A `*Profile`
       * source carries only an id, so without this the pane titles itself with
       * a UUID — see `leafTitle`. */
      initialLabel: string | null
      /** The form a blank version of this pane reopens with — an elevated tab
       * sets it, because it is never restored connected (decision 4 of
       * docs/ELEVATED_TABS_PLAN.md) and comes back as this form instead. */
      initialForm?: PaneLeaf['initial'] | null
    }
  | { type: 'paneDisconnected'; tabId: string; paneId: string }
  | { type: 'paneFocused'; tabId: string; paneId: string }
  | { type: 'paneSplit'; tabId: string; paneId: string; direction: 'horizontal' | 'vertical' }
  | { type: 'paneClosed'; tabId: string; paneId: string }
  | { type: 'panePoppedToNewTab'; tabId: string; paneId: string; poppedTab: Tab }
  | { type: 'tabAttachedToPane'; targetPaneId: string; draggedTabId: string }
  | {
      type: 'paneProfileApplied'
      tabId: string
      paneId: string
      source: ConnectionSource | null
      initial: PaneLeaf['initial']
    }

/** Recomputes a tab's title from whichever leaf is now active. Was three
 * near-identical inline blocks (in closePaneNow, popPaneToNewTab and
 * focusPane, plus the same shape again in connectPane/disconnectPane/
 * applyProfileToPane) each hand-rolling "if this changed pane happens to be
 * the active one, recompute the title, else leave it" — always safe to call
 * unconditionally instead, since re-deriving an unchanged active leaf's
 * title just reproduces what was already there. */
function retitle(tab: Tab): Tab {
  const activeLeaf = allLeaves(tab.root).find((l) => l.id === tab.activePaneId)
  return activeLeaf ? { ...tab, title: leafTitle(activeLeaf, tab.title) } : tab
}

function mapTab(tabs: Tab[], tabId: string, fn: (t: Tab) => Tab): Tab[] {
  return tabs.map((t) => (t.id === tabId ? fn(t) : t))
}

export function tabsReducer(state: TabsState, action: TabsAction): TabsState {
  switch (action.type) {
    case 'restored':
      return { tabs: action.tabs, activeTabId: action.activeTabId }

    case 'tabOpened':
      return { tabs: [...state.tabs, action.tab], activeTabId: action.tab.id }

    case 'tabClosed': {
      const idx = state.tabs.findIndex((t) => t.id === action.tabId)
      if (idx === -1) return state
      const tabs = state.tabs.filter((t) => t.id !== action.tabId)
      const activeTabId =
        state.activeTabId === action.tabId ? (tabs[idx]?.id ?? tabs[idx - 1]?.id ?? null) : state.activeTabId
      return { tabs, activeTabId }
    }

    case 'tabSelected':
      return state.activeTabId === action.tabId ? state : { ...state, activeTabId: action.tabId }

    case 'tabsReordered': {
      if (action.draggedId === action.targetId) return state
      const from = state.tabs.findIndex((t) => t.id === action.draggedId)
      const to = state.tabs.findIndex((t) => t.id === action.targetId)
      if (from === -1 || to === -1) return state
      const tabs = [...state.tabs]
      const [moved] = tabs.splice(from, 1)
      tabs.splice(to, 0, moved)
      return { ...state, tabs }
    }

    case 'paneReconnected':
      return {
        ...state,
        tabs: mapTab(state.tabs, action.tabId, (t) => ({
          ...t,
          root: updateLeaf(t.root, action.paneId, (l) => ({
            ...l,
            // Re-resolve from the profile instead of replaying the source
            // baked in at the original connect time — otherwise editing a
            // profile's host/port after connecting has no effect on
            // Reconnect, since sshProfile sources are the only ones re-read
            // fresh from disk on connect.
            source: l.initial?.id ? { protocol: 'sshProfile', profileId: l.initial.id } : l.source,
            generation: l.generation + 1,
          })),
        })),
      }

    case 'workspaceMaterialized': {
      if (action.restored.length === 0) return state
      // Consume the tab this was launched from when it has nothing in it —
      // typically the blank tab whose connect dialog was just used. Splicing
      // rather than appending also puts the workspace where that tab sat,
      // instead of after everything else.
      const target = action.originTabId ?? state.activeTabId
      const index = state.tabs.findIndex((t) => t.id === target)
      const tabs =
        index === -1 || !isBlankTab(state.tabs[index])
          ? [...state.tabs, ...action.restored]
          : [...state.tabs.slice(0, index), ...action.restored, ...state.tabs.slice(index + 1)]
      return { tabs, activeTabId: action.restored[0].id }
    }

    case 'paneConnected':
      return {
        ...state,
        tabs: mapTab(state.tabs, action.tabId, (t) =>
          retitle({
            ...t,
            root: updateLeaf(t.root, action.paneId, (l) => ({
              ...l,
              source: action.source,
              backspaceSendsCtrlH: action.backspaceSendsCtrlH,
              autoReconnect: action.autoReconnect,
              initial:
                action.initialLabel || action.initialForm
                  ? {
                      ...l.initial,
                      ...(action.initialForm ?? {}),
                      ...(action.initialLabel ? { label: action.initialLabel } : {}),
                    }
                  : l.initial,
            })),
          }),
        ),
      }

    case 'paneDisconnected':
      return {
        ...state,
        tabs: mapTab(state.tabs, action.tabId, (t) =>
          retitle({ ...t, root: updateLeaf(t.root, action.paneId, (l) => ({ ...l, source: null })) }),
        ),
      }

    case 'paneFocused':
      return {
        ...state,
        tabs: mapTab(state.tabs, action.tabId, (t) =>
          t.activePaneId === action.paneId ? t : retitle({ ...t, activePaneId: action.paneId }),
        ),
      }

    case 'paneSplit':
      return {
        ...state,
        tabs: mapTab(state.tabs, action.tabId, (t) => {
          // The limit check lives here as well as on the toolbar buttons: the
          // buttons are disabled at a limit, so this only catches a caller
          // that hasn't asked first, but silently growing a layout past what
          // the pane map can draw is worse than silently doing nothing.
          if (!canSplitLeaf(t.root, action.paneId, action.direction)) return t
          const root = splitLeaf(t.root, action.paneId, action.direction)
          // The pre-split ids are walked once into a Set rather than
          // re-walked inside the .find callback, which made this O(n²)
          // allocations per split for a question that is the same every
          // iteration. Bounded by MAX_PANES_PER_TAB either way, so this is
          // legibility more than speed.
          const oldIds = new Set(allLeaves(t.root).map((l) => l.id))
          const newLeafId = allLeaves(root).find((l) => !oldIds.has(l.id))?.id
          return { ...t, root, activePaneId: newLeafId ?? t.activePaneId }
        }),
      }

    case 'paneClosed': {
      const tab = state.tabs.find((t) => t.id === action.tabId)
      if (!tab) return state
      const newRoot = closeLeaf(tab.root, action.paneId)
      // The whole tab is gone, not just this pane — the caller (closePaneNow)
      // closes the tab itself instead in that case, which dispatches its own
      // tabClosed.
      if (!newRoot) return state
      const activePaneId = tab.activePaneId === action.paneId ? firstLeaf(newRoot).id : tab.activePaneId
      return {
        ...state,
        tabs: mapTab(state.tabs, action.tabId, () => retitle({ ...tab, root: newRoot, activePaneId })),
      }
    }

    case 'panePoppedToNewTab': {
      const tab = state.tabs.find((t) => t.id === action.tabId)
      if (!tab) return state
      const newRoot = closeLeaf(tab.root, action.paneId)
      if (!newRoot) return state // only offered when the tab actually has a split
      const activePaneId = tab.activePaneId === action.paneId ? firstLeaf(newRoot).id : tab.activePaneId
      const tabs = [
        ...mapTab(state.tabs, action.tabId, () => retitle({ ...tab, root: newRoot, activePaneId })),
        action.poppedTab,
      ]
      return { tabs, activeTabId: action.poppedTab.id }
    }

    case 'tabAttachedToPane': {
      const draggedTab = state.tabs.find((t) => t.id === action.draggedTabId)
      if (!draggedTab || draggedTab.root.type !== 'leaf' || !draggedTab.root.source) return state
      const draggedLeaf: PaneLeaf = draggedTab.root
      const tabs = state.tabs
        .filter((t) => t.id !== action.draggedTabId)
        .map((t) => {
          if (!findLeaf(t.root, action.targetPaneId)) return t
          const root = updateLeaf(t.root, action.targetPaneId, () => draggedLeaf)
          // The attached leaf keeps the dragged leaf's own id (not
          // targetPaneId), so activePaneId is remapped here if it was
          // pointing at targetPaneId — left stale, it would silently break
          // every later lookup keyed off activePaneId.
          const activePaneId = t.activePaneId === action.targetPaneId ? draggedLeaf.id : t.activePaneId
          return retitle({ ...t, root, activePaneId })
        })
      let activeTabId = state.activeTabId
      if (state.activeTabId === action.draggedTabId) {
        const idx = state.tabs.findIndex((t) => t.id === action.draggedTabId)
        activeTabId = tabs[idx]?.id ?? tabs[idx - 1]?.id ?? null
      }
      return { tabs, activeTabId }
    }

    case 'paneProfileApplied':
      return {
        ...state,
        tabs: mapTab(state.tabs, action.tabId, (t) =>
          retitle({
            ...t,
            // Also carried onto the leaf directly: connecting straight from
            // the sidebar never opens the dialog, so this is the only path
            // by which a saved session's backspace preference reaches its
            // terminal.
            root: updateLeaf(t.root, action.paneId, (l) => ({
              ...l,
              source: action.source ?? l.source,
              initial: action.initial,
              backspaceSendsCtrlH: action.initial?.backspaceSendsCtrlH ?? null,
              autoReconnect: action.initial?.autoReconnect ?? null,
            })),
          }),
        ),
      }
  }
}

/** A string that changes exactly when the active tab's visible split
 * geometry changes — which pane occupies which position, not the sizes
 * dividers are dragged to (react-resizable-panels and each Terminal's own
 * fit-on-resize already handle continuous resizing; re-running the
 * double-rAF refit on every drag frame would be pure overhead). Feeds a
 * single `useLayoutEffect` in App.tsx that replaces what used to be a
 * `refit()` call manually sprinkled at the end of every function that could
 * change what's on screen — easy to add a new one and forget it, the same
 * class of bug the pane-runtime tables had. */
export function layoutSignature(tabs: Tab[], activeTabId: string | null): string {
  const active = tabs.find((t) => t.id === activeTabId)
  return active ? `${activeTabId}:${geometry(active.root)}` : `${activeTabId}`
}

function geometry(node: PaneNode): string {
  if (node.type === 'leaf') return `L${node.id}`
  return `${node.direction[0]}(${geometry(node.children[0])},${geometry(node.children[1])})`
}
